name: TownyWars
version: 1.4.0
main: com.etysoft.townywars.TownyWars
authors: [karlov_m]
depend: [Towny]
description: A simple arcade plugin for wars with Towny.
commands:
  townwars:
    description: TownyWars main command
    usage: /<command>
    aliases: twar
permissions:
  twar.admin:
    default: op
    children:
      aun.info: true
      aun.edittown: true
    description: Allows all commands
  twar.use:
    default: op
    description: Simple information using
  twar.mayor:
    default: op
    description:  Declare a war and manage it